-- Keyword landing/tool pages generated by n8n daily pipeline
CREATE TABLE IF NOT EXISTS keyword_pages (
  id BIGSERIAL PRIMARY KEY,
  keyword TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  page_type TEXT NOT NULL CHECK (page_type IN ('brand', 'tool')),
  serp_top_url TEXT,
  target_url TEXT,
  github_path TEXT,
  github_commit TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  used_ai BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_keyword_pages_status ON keyword_pages(status);
CREATE INDEX IF NOT EXISTS idx_keyword_pages_created ON keyword_pages(created_at DESC);

ALTER TABLE keyword_pages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "keyword_pages anon read"
  ON keyword_pages FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "keyword_pages service write"
  ON keyword_pages FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
